In [80]:
import pandas as pd
import numpy as np

# Accessing data with pandas

In [81]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

# creating samples

In [82]:
coffee.sample(10)   # add random_state=seed to make sample deterministic

          Day Coffee Type  Units Sold
5   Wednesday       Latte          25
3     Tuesday       Latte          20
10   Saturday    Espresso          45
1      Monday       Latte          15
13     Sunday       Latte          35
8      Friday    Espresso          45
7    Thursday       Latte          30
9      Friday       Latte          35
11   Saturday       Latte          35
2     Tuesday    Espresso          30

# using [] (columns, conditions and integer row slicing)

In pandas, the `[]` operator can be used in several ways depending on the context. Here are the valid syntaxes:

1. **Single Column Selection**:
    - Using a string to select a single column, which returns a `Series`.
    ```python
    coffee['Day']
    ```

2. **Multiple Columns Selection**:
    - Using a list of strings to select multiple columns, which returns a `DataFrame`.
    ```python
    coffee[['Day', 'Coffee Type']]
    ```

3. **Row Slicing (only for integer-based slicing)**:
    - Using slicing syntax to select rows by index, which returns a `DataFrame`.
    ```python
    coffee[0:3]
    ```

4. **Boolean Indexing**:
    - Using a boolean mask to filter rows, which returns a `DataFrame`.
    ```python
    coffee[coffee['Units Sold'] > 30]
    ```

Note: You cannot use slicing with column names or ranges of column names directly with `[]`. For such operations, use `.loc` or `.iloc`.

## single column

using a scalar returns series

In [83]:
coffee['Day'].head()

0       Monday
1       Monday
2      Tuesday
3      Tuesday
4    Wednesday
Name: Day, dtype: object

## multiple columns

using a list returns a df

In [84]:
coffee[['Day', 'Coffee Type']].head()

         Day Coffee Type
0     Monday    Espresso
1     Monday       Latte
2    Tuesday    Espresso
3    Tuesday       Latte
4  Wednesday    Espresso

## cannot slice columns with []

In [85]:
try:
    coffee['Day':'Coffee Type']
except TypeError as te:
    print(repr(te))

# SyntaxError (not catchable)
# coffee[['Day':'Coffee Type']]

TypeError('cannot do slice indexing on RangeIndex with these indexers [Day] of type str')

## slicing rows with []

### integer row slicing

In [86]:
coffee[0:2]

      Day Coffee Type  Units Sold
0  Monday    Espresso          25
1  Monday       Latte          15

create  copy of coffee with alphabetic index

In [87]:
import string
acoffee = coffee.copy()
acoffee.index = [string.ascii_uppercase[i] for i in acoffee.index.to_list()]
acoffee.head()

         Day Coffee Type  Units Sold
A     Monday    Espresso          25
B     Monday       Latte          15
C    Tuesday    Espresso          30
D    Tuesday       Latte          20
E  Wednesday    Espresso          35

## integer slicing on alphabetical index

In [88]:
acoffee[5:7]

         Day Coffee Type  Units Sold
F  Wednesday       Latte          25
G   Thursday    Espresso          40

### alphabetic row slicing

In [89]:
acoffee['A':'B']

      Day Coffee Type  Units Sold
A  Monday    Espresso          25
B  Monday       Latte          15

# using loc

## loc select rows

### single row

using scalar for the row returns series

In [90]:
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

### multiple rows, array syntax

using list for the rows returns df

In [91]:
coffee.loc[[0, 1, 2]]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

### multiple rows, slice syntax

using slice for the rows returns df

In [92]:
coffee.loc[0:3]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

#### slice inversion

In [93]:
coffee.loc[::-1].head()

         Day Coffee Type  Units Sold
13    Sunday       Latte          35
12    Sunday    Espresso          45
11  Saturday       Latte          35
10  Saturday    Espresso          45
9     Friday       Latte          35

## loc select columns

### single column

In [94]:
coffee.loc[::-1, 'Day'].head()

13      Sunday
12      Sunday
11    Saturday
10    Saturday
9       Friday
Name: Day, dtype: object

In [96]:
coffee.loc[:, 'Day'].sort_index(ascending=False).sort_values().unique()

array(['Friday', 'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday',
       'Wednesday'], dtype=object)

In [109]:
coffee.loc[:, 'Day'].sort_values(ascending=False).drop_duplicates().to_frame()

          Day
4   Wednesday
2     Tuesday
6    Thursday
12     Sunday
10   Saturday
0      Monday
8      Friday

using a scalar for columns returns series

In [50]:
coffee.loc[0:2, 'Day']

0     Monday
1     Monday
2    Tuesday
Name: Day, dtype: object

### multiple columns

In [51]:
coffee.loc[0:2, ['Day', 'Units Sold']]

       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30

### slice of columns

In [52]:
coffee.loc[0:2, 'Day':'Units Sold']

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [53]:
coffee.loc[0:2, 'Coffee Type'::-1]

  Coffee Type      Day
0    Espresso   Monday
1       Latte   Monday
2    Espresso  Tuesday

## using iloc

###  iloc select rows

In [54]:
display(coffee.iloc[0])          # single label
display(coffee.iloc[[0, 1, 2]])  # array of labels
display(coffee.iloc[0:3])        # slice syntax
display(coffee.iloc[::-1])        # slice syntax

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

          Day Coffee Type  Units Sold
13     Sunday       Latte          35
12     Sunday    Espresso          45
11   Saturday       Latte          35
10   Saturday    Espresso          45
9      Friday       Latte          35
8      Friday    Espresso          45
7    Thursday       Latte          30
6    Thursday    Espresso          40
5   Wednesday       Latte          25
4   Wednesday    Espresso          35
3     Tuesday       Latte          20
2     Tuesday    Espresso          30
1      Monday       Latte          15
0      Monday    Espresso          25

### iloc select columns

In [55]:
display(coffee.iloc[0:2, 0])          # specify column
display(coffee.iloc[0:2, [0, 2]])     # multiple columns
display(coffee.iloc[0:2, 0:2])        # slice of columns
display(coffee.iloc[0:2, 2::-1])      # slice of columns

0    Monday
1    Monday
Name: Day, dtype: object

      Day  Units Sold
0  Monday          25
1  Monday          15

      Day Coffee Type
0  Monday    Espresso
1  Monday       Latte

   Units Sold Coffee Type     Day
0          25    Espresso  Monday
1          15       Latte  Monday

## set columns values as index

In [56]:
coffee.index = coffee.Day
coffee

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25
Thursday    Thursday    Espresso          40
Thursday    Thursday       Latte          30
Friday        Friday    Espresso          45
Friday        Friday       Latte          35
Saturday    Saturday    Espresso          45
Saturday    Saturday       Latte          35
Sunday        Sunday    Espresso          45
Sunday        Sunday       Latte          35

In [57]:
display(coffee.loc['Monday':'Tuesday']) # i would not trust this, i don't think the order is reliable

             Day Coffee Type  Units Sold
Day
Monday    Monday    Espresso          25
Monday    Monday       Latte          15
Tuesday  Tuesday    Espresso          30
Tuesday  Tuesday       Latte          20

## reset index

In [58]:
coffee = coffee.reset_index(drop=True)
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

## set values with loc

### set single value

In [59]:
display(coffee.head(2))
coffee.loc[1, 'Units Sold'] = 10
coffee.head(2)

      Day Coffee Type  Units Sold
0  Monday    Espresso          25
1  Monday       Latte          15

      Day Coffee Type  Units Sold
0  Monday    Espresso          25
1  Monday       Latte          10

### set multiple values

In [60]:
display(coffee.head())
coffee.loc[0:5, 'Units Sold'] = 0
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

         Day Coffee Type  Units Sold
0     Monday    Espresso           0
1     Monday       Latte           0
2    Tuesday    Espresso           0
3    Tuesday       Latte           0
4  Wednesday    Espresso           0

## using at, iat

get single scalar value

In [61]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
display(coffee.loc[0, 'Units Sold'])    # LABEL, column -> scalar
display(coffee.at[0, 'Units Sold'])     # LABEL, column -> scalar
display(coffee.iloc[0, 2])              # row, col      -> scalar
display(coffee.iat[0, 2])               # row, col      -> scalar

np.int64(25)

np.int64(25)

np.int64(25)

np.int64(25)

## get column

In [62]:
display(coffee.Day.head())
display(coffee['Day'].head())

0       Monday
1       Monday
2      Tuesday
3      Tuesday
4    Wednesday
Name: Day, dtype: object

0       Monday
1       Monday
2      Tuesday
3      Tuesday
4    Wednesday
Name: Day, dtype: object

## sort df

In [63]:
coffee.sort_values('Coffee Type', ascending=False).head()   # single column

         Day Coffee Type  Units Sold
1     Monday       Latte          15
3    Tuesday       Latte          20
5  Wednesday       Latte          25
7   Thursday       Latte          30
9     Friday       Latte          35

In [ ]:
coffee.sort_values(                 
    ['Coffee Type', 'Units Sold'],  # multiple columns
    ascending=[False, True]         # multiple sort order
).head()

         Day Coffee Type  Units Sold
1     Monday       Latte          15
3    Tuesday       Latte          20
5  Wednesday       Latte          25
7   Thursday       Latte          30
9     Friday       Latte          35

## iterating rows

In [110]:
for index, row in coffee.head(2).iterrows():
    display(index)
    display(row.to_list())

0

['Monday', 'Espresso', 25]

1

['Monday', 'Latte', 15]

In [66]:
for index, row in coffee.head(2).iterrows():
    display(index)
    display(row.Day)
    display(row['Coffee Type'])

0

'Monday'

'Espresso'

1

'Monday'

'Latte'