In [25]:
import pandas as pd
import numpy as np

# Accessing data with pandas

In [26]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

# creating samples

In [27]:
coffee.sample(10)   # add random_state=seed to make sample deterministic

          Day Coffee Type  Units Sold
12     Sunday    Espresso          45
10   Saturday    Espresso          45
7    Thursday       Latte          30
9      Friday       Latte          35
6    Thursday    Espresso          40
3     Tuesday       Latte          20
11   Saturday       Latte          35
5   Wednesday       Latte          25
8      Friday    Espresso          45
1      Monday       Latte          15

# using [] (columns, conditions and integer row slicing)

In pandas, the `[]` operator can be used in several ways depending on the context. Here are the valid syntaxes:

1. **Single Column Selection**:
    - Using a string to select a single column, which returns a `Series`.
    ```python
    coffee['Day']
    ```

2. **Multiple Columns Selection**:
    - Using a list of strings to select multiple columns, which returns a `DataFrame`.
    ```python
    coffee[['Day', 'Coffee Type']]
    ```

3. **Row Slicing (only for integer-based slicing)**:
    - Using slicing syntax to select rows by index, which returns a `DataFrame`.
    ```python
    coffee[0:3]
    ```

4. **Boolean Indexing**:
    - Using a boolean mask to filter rows, which returns a `DataFrame`.
    ```python
    coffee[coffee['Units Sold'] > 30]
    ```

Note: You cannot use slicing with column names or ranges of column names directly with `[]`. For such operations, use `.loc` or `.iloc`.

## single column

using a scalar returns series

In [47]:
coffee['Day'].head()

0       Monday
1       Monday
2      Tuesday
3      Tuesday
4    Wednesday
Name: Day, dtype: object

## multiple columns

using a list returns a df

In [50]:
coffee[['Day', 'Coffee Type']].head()

         Day Coffee Type
0     Monday    Espresso
1     Monday       Latte
2    Tuesday    Espresso
3    Tuesday       Latte
4  Wednesday    Espresso

## cannot slice columns with []

In [65]:
try:
    coffee['Day':'Coffee Type']
except TypeError as te:
    print(repr(te))

# SyntaxError (not catchable)
# coffee[['Day':'Coffee Type']]

TypeError('cannot do slice indexing on RangeIndex with these indexers [Day] of type str')

## slicing rows with []

### integer row slicing

In [66]:
coffee[0:2]

      Day Coffee Type  Units Sold
0  Monday    Espresso          25
1  Monday       Latte          15

create  copy of coffee with alphabetic index

In [74]:
import string
acoffee = coffee.copy()
acoffee.index = [string.ascii_uppercase[i] for i in acoffee.index.to_list()]
acoffee.head()

         Day Coffee Type  Units Sold
A     Monday    Espresso          25
B     Monday       Latte          15
C    Tuesday    Espresso          30
D    Tuesday       Latte          20
E  Wednesday    Espresso          35

## integer slicing on alphabetical index

In [77]:
acoffee[5:7]

         Day Coffee Type  Units Sold
F  Wednesday       Latte          25
G   Thursday    Espresso          40

### alphabetic row slicing

In [ ]:
acoffee['A':'B']

      Day Coffee Type  Units Sold
A  Monday    Espresso          25
B  Monday       Latte          15

# using loc

## loc select rows

### single row

using scalar for the row returns series

In [28]:
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

### multiple rows, array syntax

using list for the rows returns df

In [34]:
coffee.loc[[0, 1, 2]]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

### multiple rows, slice syntax

using slice for the rows returns df

In [33]:
coffee.loc[0:3]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

#### slice inversion

In [36]:
coffee.loc[::-1].head()

         Day Coffee Type  Units Sold
13    Sunday       Latte          35
12    Sunday    Espresso          45
11  Saturday       Latte          35
10  Saturday    Espresso          45
9     Friday       Latte          35

## loc select columns

### single column

using a scalar for columns returns series

In [37]:
coffee.loc[0:2, 'Day']

0     Monday
1     Monday
2    Tuesday
Name: Day, dtype: object

### multiple columns

In [38]:
coffee.loc[0:2, ['Day', 'Units Sold']]

       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30

### slice of columns

In [39]:
coffee.loc[0:2, 'Day':'Units Sold']

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [40]:
coffee.loc[0:2, 'Coffee Type'::-1]

  Coffee Type      Day
0    Espresso   Monday
1       Latte   Monday
2    Espresso  Tuesday

## using iloc

###  iloc select rows

In [ ]:
display(coffee.iloc[0])          # single label
display(coffee.iloc[[0, 1, 2]])  # array of labels
display(coffee.iloc[0:3])        # slice syntax
display(coffee.iloc[::-1])        # slice syntax

### iloc select columns

In [ ]:
display(coffee.iloc[0:2, 0])          # specify column
display(coffee.iloc[0:2, [0, 2]])     # multiple columns
display(coffee.iloc[0:2, 0:2])        # slice of columns
display(coffee.iloc[0:2, 2::-1])      # slice of columns

## set columns values as index

In [ ]:
coffee.index = coffee.Day
coffee

In [ ]:
display(coffee.loc['Monday':'Tuesday']) # i would not trust this, i don't think the order is reliable

## reset index

In [ ]:
coffee = coffee.reset_index(drop=True)
coffee

## set values with loc

### set single value

In [ ]:
display(coffee.head(2))
coffee.loc[1, 'Units Sold'] = 10
coffee.head(2)

### set multiple values

In [ ]:
display(coffee.head())
coffee.loc[0:5, 'Units Sold'] = 0
coffee.head()

## using at, iat

get single scalar value

In [ ]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
display(coffee.loc[0, 'Units Sold'])    # LABEL, column -> scalar
display(coffee.at[0, 'Units Sold'])     # LABEL, column -> scalar
display(coffee.iloc[0, 2])              # row, col      -> scalar
display(coffee.iat[0, 2])               # row, col      -> scalar

## get column

In [ ]:
display(coffee.Day.head())
display(coffee['Day'].head())

## sort df

In [ ]:
coffee.sort_values('Coffee Type', ascending=False).head()   # single column

In [ ]:
coffee.sort_values(                 # multiple columns
    ['Coffee Type', 'Units Sold'],
    ascending=[False, True]
).head()

## iterating rows

In [ ]:
for index, row in coffee.head(2).iterrows():
    display(index)
    display(row)

In [ ]:
for index, row in coffee.head(2).iterrows():
    display(index)
    display(row.Day)
    display(row['Coffee Type'])