In [1]:
import pandas as pd
import numpy as np

# Filtering data

In [2]:
bios = pd.read_csv('./data/bios.csv')
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

## create panda series of boolean values for the condition

In [13]:
display(len(bios))
is_tall = bios.height_cm > 215   # get boolean series for condition
display(type(is_tall))
display(len(is_tall))
true_is_tall = is_tall[is_tall]          # filter true values from series
display(len(true_is_tall))
true_is_tall.head()

145500

pandas.core.series.Series

145500

35

5089    True
5583    True
5673    True
5716    True
5781    True
Name: height_cm, dtype: bool

## use the panda series to filter df with []

In [14]:
display(len(bios[is_tall]))
display(bios[is_tall].head())
bios[bios['height_cm'] > 215].head()

35

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5089,5108,Viktor Pankrashkin,1957-06-19,Moskva (Moscow),Moskva,RUS,Soviet Union,220.0,112.0,1993-07-24
5583,5606,Paulinho Villas Boas,1963-01-26,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN
5716,5739,Uwe Blab,1962-03-26,München (Munich),Bayern,GER,Germany West Germany,218.0,110.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5089,5108,Viktor Pankrashkin,1957-06-19,Moskva (Moscow),Moskva,RUS,Soviet Union,220.0,112.0,1993-07-24
5583,5606,Paulinho Villas Boas,1963-01-26,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN
5716,5739,Uwe Blab,1962-03-26,München (Munich),Bayern,GER,Germany West Germany,218.0,110.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN

## filter df using loc with condition and columns

In [5]:
bios.loc[
    bios['height_cm'] > 215,    # filter
    ['name', 'height_cm']       # output columns
].head()

                       name  height_cm
5089     Viktor Pankrashkin      220.0
5583   Paulinho Villas Boas      217.0
5673         Gunther Behnke      221.0
5716               Uwe Blab      218.0
5781         Tommy Burleson      223.0

## alternate syntax: select columns from filtered df

In [6]:
bios[bios['height_cm']>215][['name', 'height_cm']].head()

                       name  height_cm
5089     Viktor Pankrashkin      220.0
5583   Paulinho Villas Boas      217.0
5673         Gunther Behnke      221.0
5716               Uwe Blab      218.0
5781         Tommy Burleson      223.0

## multiple conditions

In [15]:
bios[
    (bios['height_cm']>215) &                                   # bitwise and
    (bios['born_country'].str.casefold() == 'usa'.casefold())
][
    ['name', 'height_cm', 'born_country']
]

                    name  height_cm born_country
5781      Tommy Burleson      223.0          USA
6722    Shaquille O'Neal      216.0          USA
6937      David Robinson      216.0          USA
123850    Tyson Chandler      216.0          USA

## string accessor

In [8]:
bios[bios['name'].str.contains('bob|keith', case=False)].head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
756,760,Bobby Powell,1881-04-02,Victoria,British Columbia,CAN,Canada,NaN,NaN,1917-04-28
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3422,3434,Bobby Kelsey,1938-12-08,London,England,GBR,Great Britain,177.0,62.0,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
3513,3525,Bobby Wells,1961-05-15,London,England,GBR,Great Britain,193.0,91.0,NaN

## .isin()

In [16]:
bios[
    (bios['born_country'].str.lower()                   # str accessor
    .isin('usa ita fra'.split()))                       # filter for values in list
    &                                                   # bitwise and
    (bios['name'].str.lower().str.startswith('fab'))    # chained str accessors
].sample(5).head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
71467,72007,Fabio Grossi,1967-09-03,Milano,Milano,ITA,Italy,185.0,72.0,NaN
111978,113227,Fabio Masotti,1974-06-03,Udine,Udine,ITA,Italy,NaN,NaN,NaN
117274,118760,Fabio Pasini,1980-08-23,Gazzaniga,Bergamo,ITA,Italy,179.0,76.0,NaN
37991,38293,Fabrizio Biondi,1954-11-07,Livorno,Livorno,ITA,Italy,181.0,82.0,NaN
4089,4103,Fabrizio De Chiara,1971-11-14,Cologno Monzese,Milano,ITA,Italy,178.0,70.0,1996-11-17

## using .query

In [10]:
bios.query('born_country == "ITA" and born_city == "Torino"').head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
801,805,Paola Bologna,1898-08-20,Torino,Torino,ITA,Italy,NaN,NaN,1960-01-13
1555,1562,Dante Carbini,1973-08-09,Torino,Torino,ITA,Italy,188.0,86.0,NaN
5512,5533,Rosanna Vergnano,1954-05-21,Torino,Torino,ITA,Italy,172.0,64.0,NaN
10088,10144,Maria Cristina Giai Pron,1974-08-21,Torino,Torino,ITA,Italy,168.0,60.0,NaN
10158,10214,Eligio Valentino,1925-07-19,Torino,Torino,ITA,Italy,NaN,NaN,2012-10-10

In [ ]:
bios.query(
    'born_country.str.lower() == "ita" '
    'and '
    'born_city.str.lower() == "torino"'
).head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
801,805,Paola Bologna,1898-08-20,Torino,Torino,ITA,Italy,NaN,NaN,1960-01-13
1555,1562,Dante Carbini,1973-08-09,Torino,Torino,ITA,Italy,188.0,86.0,NaN
5512,5533,Rosanna Vergnano,1954-05-21,Torino,Torino,ITA,Italy,172.0,64.0,NaN
10088,10144,Maria Cristina Giai Pron,1974-08-21,Torino,Torino,ITA,Italy,168.0,60.0,NaN
10158,10214,Eligio Valentino,1925-07-19,Torino,Torino,ITA,Italy,NaN,NaN,2012-10-10

## using .isin() inside .query() via @ operator

In [12]:
states = 'ITA FRA USA'.lower().split()
bios.query(
    'born_country.str.lower().isin(@states)'
).sample(5)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
77592,78183,Edward Bushnell,1876-12-05,Republican City,Nebraska,USA,United States,NaN,NaN,1951-01-05
85291,85971,Norbert Gasser,1957-05-18,Bolzano,Bolzano-Bozen,ITA,Italy,195.0,91.0,NaN
41776,42096,Georges Bordier,1880-04-07,Nancy,Meurthe-et-Moselle,FRA,France,NaN,NaN,1948-10-09
113651,114950,Filippo Campioli,1982-02-21,Modena,Modena,ITA,Italy,193.0,82.0,NaN
135219,138367,Jonathan Cheever,1985-04-17,Boston,Massachusetts,USA,United States,178.0,86.0,NaN