In [1]:
import pandas as pd
import numpy as np

In [2]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

# Add/Remove columns

## add price column

In [3]:
coffee['price'] = 4.99
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

### condition series

In [4]:
coffee['Coffee Type']=='Espresso'

0      True
1     False
2      True
3     False
4      True
5     False
6      True
7     False
8      True
9     False
10     True
11    False
12     True
13    False
Name: Coffee Type, dtype: bool

### where np array

In [5]:
# print((coffee['Coffee Type']=='Espresso').to_list())

npw = np.where(                             # numpy where (ternary if)
    coffee['Coffee Type']=='Espresso',      # condition, boolean series
    3.99,                                   # if true, cellcis 3.99
    5.99                                    # else, cells 5.99
)

print((coffee['Coffee Type']=='Espresso').to_list())
print(npw.tolist())

prices = list(zip(
    (coffee['Coffee Type']=='Espresso').to_list(),
    npw.tolist()
))

# print({i:dict([prices[i]]) for i in range(len(prices))})
print([dict([t]) for t in prices])

[True, False, True, False, True, False, True, False, True, False, True, False, True, False]
[3.99, 5.99, 3.99, 5.99, 3.99, 5.99, 3.99, 5.99, 3.99, 5.99, 3.99, 5.99, 3.99, 5.99]
[{True: 3.99}, {False: 5.99}, {True: 3.99}, {False: 5.99}, {True: 3.99}, {False: 5.99}, {True: 3.99}, {False: 5.99}, {True: 3.99}, {False: 5.99}, {True: 3.99}, {False: 5.99}, {True: 3.99}, {False: 5.99}]

In [6]:
coffee['new-price'] = np.where(             # numpy where (ternary if)
    coffee['Coffee Type']=='Espresso',      # condition, boolean series
    3.99,                                   # if true, cellcis 3.99
    5.99                                    # else, cells 5.99
)
coffee.head()

         Day Coffee Type  Units Sold  price  new-price
0     Monday    Espresso          25   4.99       3.99
1     Monday       Latte          15   4.99       5.99
2    Tuesday    Espresso          30   4.99       3.99
3    Tuesday       Latte          20   4.99       5.99
4  Wednesday    Espresso          35   4.99       3.99

## remove column

In [7]:
coffee.drop(columns='price', inplace=True)
coffee.head()

         Day Coffee Type  Units Sold  new-price
0     Monday    Espresso          25       3.99
1     Monday       Latte          15       5.99
2    Tuesday    Espresso          30       3.99
3    Tuesday       Latte          20       5.99
4  Wednesday    Espresso          35       3.99

In [8]:
coffee['price'] = 4.99
coffee = coffee[['Day', 'Coffee Type', 'Units Sold', 'new-price']]  # create new df with the selected columns
coffee.head()

         Day Coffee Type  Units Sold  new-price
0     Monday    Espresso          25       3.99
1     Monday       Latte          15       5.99
2    Tuesday    Espresso          30       3.99
3    Tuesday       Latte          20       5.99
4  Wednesday    Espresso          35       3.99

In [9]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new-price']
coffee.head()

         Day Coffee Type  Units Sold  new-price  revenue
0     Monday    Espresso          25       3.99    99.75
1     Monday       Latte          15       5.99    89.85
2    Tuesday    Espresso          30       3.99   119.70
3    Tuesday       Latte          20       5.99   119.80
4  Wednesday    Espresso          35       3.99   139.65

## Rename column

In [10]:
coffee = coffee.copy().rename(columns={'new-price': 'price'})
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

## add a new column from existing

In [11]:
bios = pd.read_csv('./data/bios.csv')
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

### add first name

In [23]:
bios['first-name'] = bios['name'].str.split().str[0]    # create first name col

# move first-name to second place
columns = bios.columns.tolist()                         # get col names
columns.insert(1,                                       # move to position 1
        columns.pop(columns.index('first-name'))        # get first name column by index
)
bios = bios[columns]                                    # create df 
bios.head()

,athlete_id,first-name,name,born-datetime,born_date,born-year,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height-category,category
0,1,Jean-François,Jean-François Blanchy,1886-12-12,1886-12-12,1886.0,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,HeavyWeight
1,2,Arnaud,Arnaud Boetsch,1969-04-01,1969-04-01,1969.0,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,MiddleWeight
2,3,Jean,Jean Borotra,1898-08-13,1898-08-13,1898.0,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,MiddleWeight
3,4,Jacques,Jacques Brugnon,1895-05-11,1895-05-11,1895.0,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,LightWeight
4,5,Albert,Albert Canet,1878-04-17,1878-04-17,1878.0,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,HeavyWeight

### add birth year

In [13]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   first-name    145500 non-null  object
 2   name          145500 non-null  object
 3   born_date     143693 non-null  object
 4   born_city     110908 non-null  object
 5   born_region   110908 non-null  object
 6   born_country  110908 non-null  object
 7   NOC           145499 non-null  object
 8   height_cm     106651 non-null  float64
 9   weight_kg     102070 non-null  float64
 10  died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 12.2+ MB

In [24]:
bios['born-datetime'] = pd.to_datetime(bios['born_date'])

columns = bios.columns.tolist()                         # get col names
born_date_idx = columns.index('born_date')              # get born date position
columns.insert(born_date_idx,                           # move to born_date position
        columns.pop(columns.index('born-datetime'))     # get curr index
)
bios = bios[columns]                                    # create df 
bios.head()

,athlete_id,first-name,name,born_date,born-datetime,born-year,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height-category,category
0,1,Jean-François,Jean-François Blanchy,1886-12-12,1886-12-12,1886.0,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,HeavyWeight
1,2,Arnaud,Arnaud Boetsch,1969-04-01,1969-04-01,1969.0,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,MiddleWeight
2,3,Jean,Jean Borotra,1898-08-13,1898-08-13,1898.0,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,MiddleWeight
3,4,Jacques,Jacques Brugnon,1895-05-11,1895-05-11,1895.0,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,LightWeight
4,5,Albert,Albert Canet,1878-04-17,1878-04-17,1878.0,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,HeavyWeight

In [15]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   first-name     145500 non-null  object
 2   name           145500 non-null  object
 3   born-datetime  143693 non-null  datetime64[ns]
 4   born_date      143693 non-null  object
 5   born_city      110908 non-null  object
 6   born_region    110908 non-null  object
 7   born_country   110908 non-null  object
 8   NOC            145499 non-null  object
 9   height_cm      106651 non-null  float64
 10  weight_kg      102070 non-null  float64
 11  died_date      33940 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 13.3+ MB

In [25]:
bios['born-year'] = bios['born-datetime'].dt.year

columns = bios.columns.tolist()                         # get col names
born_date_idx = columns.index('born_date')              # get born_date position
columns.insert(born_date_idx,
        columns.pop(columns.index('born-year'))         # get curr index
)
bios = bios[columns]                                    # create df 
bios.head()

,athlete_id,first-name,name,born-year,born_date,born-datetime,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height-category,category
0,1,Jean-François,Jean-François Blanchy,1886.0,1886-12-12,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,HeavyWeight
1,2,Arnaud,Arnaud Boetsch,1969.0,1969-04-01,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,MiddleWeight
2,3,Jean,Jean Borotra,1898.0,1898-08-13,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,MiddleWeight
3,4,Jacques,Jacques Brugnon,1895.0,1895-05-11,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,LightWeight
4,5,Albert,Albert Canet,1878.0,1878-04-17,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,HeavyWeight

# Save df

In [17]:
bios.to_csv('data/bios-new.csv', index=False)

## .apply()

In [18]:
bios['height-category'] = bios['height_cm'].apply(
    lambda x: 'Short' if x < 165 else (
        'Average' if x < 185 else 'Tall'
    )
)
bios[['name', 'height-category']].head()

                    name height-category
0  Jean-François Blanchy            Tall
1         Arnaud Boetsch         Average
2           Jean Borotra         Average
3        Jacques Brugnon         Average
4           Albert Canet            Tall

In [19]:
def categorize_athlete(row:pd.Series):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'LightWeight'
    elif row['height_cm'] < 185 or row['weight_kg'] <= 80:
        return 'MiddleWeight'
    else:
        return 'HeavyWeight'


bios['category'] = bios.apply(categorize_athlete, axis=1)
bios[['name', 'category']].head()

                    name      category
0  Jean-François Blanchy   HeavyWeight
1         Arnaud Boetsch  MiddleWeight
2           Jean Borotra  MiddleWeight
3        Jacques Brugnon   LightWeight
4           Albert Canet   HeavyWeight